version: '2'
services:
  influxdb:
    image: influxdb:1.8.2
    ports:
        - '8086:8086'
    volumes:
        - /media/usb-disk/influxdb:/influxdb-storage:rw
        - ./influxdb/provisioning/:/docker-entrypoint-initdb.d/
        - ./influxdb/conf/influxdb.conf:/etc/influxdb/influxdb.conf:ro
    environment:
        - INFLUXDB_DB=monitoring
        - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
        - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}
        - INFLUXDB_META_DIR=/influxdb-storage/meta
  grafana:
    image: grafana/grafana:7.1.5
    ports:
      - '3000:3000'
    volumes:
      - /media/usb-disk/grafana:/grafana-storage:rw
      - ./grafana/provisioning/:/etc/grafana/provisioning
    depends_on:
         - influxdb
    environment:
         - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
         - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
  telegraf:
    image: telegraf:1.15.2
    volumes:
      - /media/usb-disk/telegraf:/telegraf-storage
      - ./telegraf/conf/telegraf.conf:/etc/telegraf/telegraf.conf:ro 
      - /var/run/docker.sock:/var/run/docker.sock
