version: '2'
services:
  influxdb:
    image: influxdb:1.8.2
    ports:
        - '8086:8086'
    volumes:
        - influxdb-storage:/media/usb-disk/influxdb
        - ./influxdb/provisioning/:/docker-entrypoint-initdb.d/
    environment:
        - INFLUXDB_DB=monitoring
        - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
        - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}
  grafana:
    image: grafana/grafana:7.1.5
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/media/usb-disk/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning
    depends_on:
         - influxdb
    environment:
         - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
         - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
  telegraf:
    image: telegraf:1.15.2
    volumes:
      - telegraf-storage:/media/usb-disk/telegraf
      - ./telegraf/conf/telegraf.conf:/etc/telegraf/telegraf.conf:ro 
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
      telegraf-storage:
      influxdb-storage:
      grafana-storage:
